# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fedora-gcc-openssl:
    strategy:
      matrix:
        container: ["fedora:latest"]
        # systemCurl: [ON, OFF]
        buildType: [Debug, Release]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - name: Update package list
      run: dnf update -y
    - name: Install Dependencies
      run: |
        dnf install -y gcc clang git gcc gdb make openssl-devel libcurl-devel cmake
        dnf install -y glib2-devel autoconf gtk-doc ostree-devel bison liblzf e2fsprogs-devel xz-devel gpgme-devel fuse-devel
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Build" # & Test"
      env:
        CPR_BUILD_TESTS: OFF
        CPR_BUILD_TESTS_SSL: OFF
        CPR_FORCE_OPENSSL_BACKEND: ON
        USE_SYSTEM_CURL: ${{ matrix.systemCurl }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ github.workspace }}/build
        source-dir: ${{ github.workspace }}
        cc: gcc
        cxx: g++
        build-type: ${{ matrix.buildType }}
        run-test: false
        ctest-options: ${{ env.CTEST_OPTIONS }}
